config/routes.rb
Websitecms::Application.routes.draw do
  resources :contacts

  get "pages/index"
  get "pages/about"
  get "pages/speakers"
  get "pages/schedule"
  get "pages/blog"
  get "pages/contact"
  get "pages/videos"
  
  get "pages/talk"
  get "pages/sponsors"
  get "pages/venue"

  match "sessions" => "pages#sessions"

   root :to => 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @on_home_page = true
  end

  def talk
  end

  def sponsors
  end

  def speakers
  end

  def venue
  end

  def videos
  end

  def contact
  end

  def schedule
  end

  def sessions
    redirect_to "http://html5tx2013.sched.org/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<section class="inner clearfix">
   <div class="inner-content">

    <h1>Listing contacts</h1>

    <table>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Message</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
  
  </div>
</section>

app/views/contacts/new.html.erb
<section class="inner clearfix">
   <div class="inner-content">
      <h2>Contact Us</h2>
      <p>Have a question or comment for us? Perhaps we can help. Just complete the form below and we'll be in touch soon.</p>
      <p>Interested in sponsoring? email us directly at <a href="mailto:sponsorship@html5tx.com">sponsorship@html5tx.com</a></p>
   </div>
</section>
<section class="inner clearfix">
   <div class="half inner-content footered">
      <%= form_for(@contact) do |f| %>
         <% if @contact.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

            <ul>
            <% @contact.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
         <% end %>
         <p>
            <label for="name">Name:</label>
            <input id="name" name="name" maxlength="48" required placeholder="Enter your name" type="text" />
         </p>
         <p>
            <label for="email">E-mail:</label>
            <input id="email" name="email" maxlength="48" required placeholder="ex. foo@bar.com" type="email" title="ex. foo@bar.com" />
         </p>
         <p>
            <label class="textarea" for="message">Anything to tell us?</label>
            <textarea id="message" name="message"></textarea>
         </p>
         <button type="submit">Submit</button>
      <% end %>
   </div>
   <div class="half">
      <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=St.+Edward's+University+Ragsdale+Center+Austin,+TX&amp;aq=&amp;sll=31.168934,-100.076842&amp;sspn=17.815351,28.54248&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Ragsdale+Center,+Moody,+Austin,+Texas+78704&amp;ll=30.22947,-97.756525&amp;spn=0.006227,0.006968&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
   </div>
</section>

app/views/contacts/show.html.erb
<section class="inner clearfix">
   <div class="inner-content center">
      <h2>Thanks for your email!</h2>
      <p>We'll be in touch soon. If you've contacted us regarding a sponsorship, please email us at: <a href="mailto:sponsorship@html5tx.com">sponsorship@html5tx.com</a></p>
   </div>
</section>

app/views/layouts/application.html.erb
<!doctype html>

<html lang="en">

<head>
   <meta charset="utf-8">
   <title>HTML5.tx 2013</title>
   <meta name="viewport" content="width=device-width">
   <meta name="keywords" content="html5, conference, texas, javascript, css, html">
   <meta name="description" content="Website for the HTML5.tx Conference, held annualy in Austin, TX">
   <%= stylesheet_link_tag "application", :media => "all" %>
   <link type="text/plain" rel="author" href="/humans.txt" />
   <script src="/js/html5shiv.js"></script>
</head>

<body class="<%= @on_home_page && "home" %>">
   <header class="group" role="banner">
      <h1>HTML5.tx 2013<span class="cog cog-m"></span></h1>
      <div class="eagle"></div>
      <nav class="l-navigation" role="navigation">
         <ul class="left">
            <li class="first"><a href="/">H<small>o</small>me</a></li>
            <li><a href="/pages/about">Ab<small>ou</small>t</a></li>
            <li class="last"><a href="/pages/schedule">Sch<small>e</small>d<small>u></small>l<small>e</small></a></li>
         </ul>
         <ul class="right">
            <li class="first"><a href="/pages/blog">N<small>e</small>ws</a></li>
            <li><a href="/pages/contact">C<small>o</small>nt<small>a</small>ct</a></li>
            <li class="last"><a href="http://2011.html5tx.com/videos">V<small>i</small>d<small>eo</small>s</a></li>
            <!-- <li class="last"><a href="http://2011.html5tx.com/">2011</a></li> -->
         </ul>
      </nav>
   </header>
   <div class="group" role="main">
      <%= yield %>
   </div>
   <!--<div class="group" role="main">
      <section class="column social">
         <a class="social-self" href="#">HTML5.tx 2013</a>
      </section>
      <section class="column social last">
         <a class="social-blog" href="#">Read the Blog</a>
         <span class="social-media">
            <a class="twitter" href="#">Twitter</a>
            <a class="facebook" href="#">Facebook</a>
         </span>
      </section>
   </div>-->
   <footer class="group">
      <nav>
         <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/pages/about">About</a></li>
            <li><a href="/pages/schedule">Schedule</a></li>
            <li><a href="/pages/speakers">Speakers</a></li>
            <li><a href="/pages/sponsors">Sponsors</a></li>
            <li><a href="/pages/blog">News</a></li>
            <li><a href="/pages/contact">Contact</a></li>
            <li><a href="http://2011.html5tx.com/videos">Videos</a></li>
         </ul>
      </nav>
      <ul>
         <li><span class="text">Copyright 2012 HTML5.tx</span></li>
         <li><hr /></li>
         <li><a href="http://driftingcreatives.com/">Design: Drifting Creatives</a></li>
      </ul>
   </footer>
   
   <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-2061518-5']);
      _gaq.push(['_setDomainName', 'html5tx.com']);
      _gaq.push(['_trackPageview']);

      (function() {
         var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
         ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
         var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
   </script>
</body>

</html>

app/views/pages/about.html.erb
<section class="intro-em group" role="main">
   <h2>About</h2>
   <p>HTML5.tx is the premier event for web designers, developers and technologists in Texas. Our <a href="http://2011.html5tx.com">inaugural event</a> was held in Austin in 2011, and the second edition is slated for Feb 2nd, 2013. Check out last year's <a href="https://vimeo.com/36094284">promo video</a> to get a preview of what's in store for 2013.</p>
   <p>HTML5.tx is a place for designers and developers of all disciplines and backgrounds to learn from web experts and each other about HTML, CSS, JavaScript and the future of the web. All are welcome. If you love the web, you can expect to be surrounded with some of the best web-heads in Texas and beyond.</p>
</section>
<div class="group" role="main">
   <section class="column frame content-frame">
      <h2>Event Information</h2>
      <p>HTML5.tx will feature a great line-up of speakers, workshops, social events, and people from most of the web technologies out there. You don't want to miss it.</p>
      <p>The conference will be Saturday, February 2nd, 2013, from 8 a.m. to 5 p.m. at St. Edward's Ragsdale Center and will cost $99. Sessions will be offered in both &quot;Getting Started&quot; and &quot;Digging Deeper&quot; tracks. We'll also  bring back last year's popular Open Spaces sessions, so if group discussion is more your style, we'll have plenty of that, too! Regardless of your comfort with the web, you'll find content just right for you.</p>
      <p>For 2013, we're excited to offer, in addition to the conference, in-depth CSS and JavaScript workshops from industry experts <a href="http://lanyrd.com/profile/pamelafox/">Pamela Fox</a> and <a href="http://lanyrd.com/profile/estellevw/">Estelle Weyl</a>. When you purchase tickets, you can choose just the Saturday conference, one or both of the workshops&mdash;or any combination of the three.</p>
      <h2>Conference Schedule</h2>
      <p>Visit the <a href="/pages/schedule">conference schedule page</a> for details on conference sessions, workshops, and social events.</p>
      <h2><a id="hacky-hour">Hacky Hour</a></h2>
	  <p><a href="https://github.com/HTML5tx/HackyHour">Your Hacky Hour Challenges</a></p>
      <p>Picture it: It's Saturday evening, at the conclusion of an exhilarating day of learning about HTML, JavaScript, and CSS. Your brain is crackling with all the new concepts you want to try out. You're not ready for the conference to be over!</p>
      <p>And why should it be? Join us at Capital Factory for food, beverages, conversation, and code. More than a happy hour, we're hosting a Hacky Hour. Enjoy dinner and refreshments with your fellow conference attendees and keep the conversation going. If you feel inspired to bust out your laptop to share something you learned that day, that's cool, too; we'll have tables and wi-fi in Capital Factory's inspiring workspace.</p>
      <p>As a matter of fact, we've asked our conference speakers to extend their generosity and offer <a href="https://github.com/HTML5tx/HackyHour">fun challenges to take the next step</a>, building on what you learned in their sessions. It's a great way share your passion for the web with folks who get where you're coming from.</p>
      <p>After the conference closing remarks at the St. Edward's Ragsdale Center, head over to Capital Factory and join us!</p>
   </section>
   <section class="column last">
      <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=St.+Edward's+University+Ragsdale+Center+Austin,+TX&amp;aq=&amp;sll=31.168934,-100.076842&amp;sspn=17.815351,28.54248&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Ragsdale+Center,+Moody,+Austin,+Texas+78704&amp;ll=30.22947,-97.756525&amp;spn=0.006227,0.006968&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
      <div class="column">
         <h2>Conference Location</h2>
         <p><a href="http://www.stedwards.edu/map/maincampus">St. Edward's University,<br />Ragsdale Center</a><br />
            Saturday Conference Day<br />
            3001 South Congress Ave.<br />
            Austin, TX 78704<br />
            512-448-8400</p>
      </div>
      <div class="column">
         <h2>Other Event Location</h2>
         <p><a href="http://www.capitalfactory.com/">Capital Factory</a><br />
            Friday and Sunday workshops, Saturday evening party<br />
            701 Brazos Street<br />
            Suite 1601<br />
            Austin, TX  78701</p>
      </div>
      <div style="clear:both">
         <h2><a id="capital-factory">Getting to Capital Factory</a></h2>
         <p>Capital Factory is a co-working space on the 16th floor of the building that houses the Omni Hotel. You might want to <a href="http://www.capmetro.org/metrorail.aspx?id=312">take the MetroRail train to the Downtown station</a> or use the <a href="http://www.capmetro.org/planner/">CapMetro trip planner to find a convenient bus</a>.</p>
         <p>On Saturday, you'll want to travel from the conference at St. Edward's University to the party at Capital Factory. Two bus lines make that a convenient trip: 1L and 1M. The bus costs $1 each way, they run until midnight on Saturday, and they solve the question of parking downtown.</p>
      </div>
   </section>
</div>

app/views/pages/blog.html.erb
<div class="intro group" role="main">
   <h2>Blog &amp; News</h2>
   <p>From time-to-time, we'll post important news and updates related to HTML5.tx here. If you have any direct questions for us, please <a href="/pages/contact">visit our contact page</a>.</p>
</div>
<div class="group" role="main">
   <section class="column column-em">
      <div class="frame content-frame">
         <h3>HTML5.tx 2013 is Sold Out!</h3>
         <p>01.28.2013</p>
         <p>This year's HTML5.tx conference is officially sold out! Thanks to everyone who bought a ticket to the conference and workshops.</p>
         <p>If you happen to have a ticket you no longer need, please let us know by emailing <a href="mailto:event@html5tx.com">event@html5tx.com</a> and we'll try to match you with someone in need of one. Unfortunately, we're not able to offer refunds at this time.</p>
         <p>See you this weekend!</p>
      </div>
      
      
      <div class="frame content-frame">
         <h3>Tickets Are On Sale Now!</h3>
         <p>10.24.2012</p>
         <p>We are happy to announce that tickets for HTML5.tx 2013 are available now! To get your ticket, head on over to <a href="http://html5tx.thundertix.com/">html5tx.thundertix.com</a>!
         For this year's event, we've added two full-day training classes, book-ended to the conference. On Friday, Estelle Weyl will be delivering her popular <a href="http://lanyrd.com/2013/html5tx/szcdh/">CSS3: From Novice to Ninja</a> course, while on Sunday, Pamela Fox will be delivering an <a href="http://lanyrd.com/2013/html5tx/szcdm/">Advanced JavaScript</a> training course. Each class is $149 as a standalone purchase, and the three-day conference and training class is $349.</p>
         <p>HTML5.tx is going to be bigger and better this year, and we hope you'll <a href="http://html5tx.thundertix.com/">join us</a>!</p>
      </div>
      <div class="frame content-frame">
         <h3>Call for Proposals is Open!</h3>
         <p>09.27.2012</p>
         <p>By Jeff Carouth. Cross-posted from <a href="http://carouth.com/blog/2012/09/7/html5-dot-tx-2013-cfp-is-open">carouth.com/blog/2012/09/7/html5-dot-tx-2013-cfp-is-open</a></p>
         <p>Last year I was one of the volunteers that helped organize HTML5.tx 2011 in Austin, Texas. The event was very successful and I couldn’t have been more proud to have played a part in it.</p>
         <p>We are putting on the next edition of the conference-–it will take place on February 2, 2013-–and I am pleased to announce the Call for Proposals is now open for your submissions. This year we have several speakers that are already committed to speak at the event and we have saved slots for you to speak. We want to hear from the community so this is your chance.</p>
         <p>Submissions will be accepted starting today and running through October 28, 2012 at 11:59:59 p.m. Submit as many proposals as you’d like. We have reserved slots for full sessions (50 minutes in length) and are introducing a new format this year composed of three 10-minute talks back to back. This is a play on “lightning talks” and is aimed to give new presenters an opportunity to give a less stressful session on a more focused topic. However, if you’re an experienced speaker with a great idea for a 10-minute talk, please submit one.</p>
         <p>Along the lines of wanting to encourage new presenters, this year we want to offer a sort-of mentorship opportunity. Members of the HTML5.tx organizer team have volunteered to help mentor any speaker that might wish to speak at the event but needs a little help developing his or her topic or slides. We will be available for questions or to review anything you might need help with. Please don’t let fear keep you from submitting a proposal.</p>
         <p>I can't wait to see what you want to talk about. Submit today at <a href="http://bit.ly/cfp-2013">http://bit.ly/cfp-2013</a>.</p>
      </div>
      <div class="frame content-frame">
         <h3>Registration, Call for Speakers, and More</h3>
         <p>09.17.2012</p>
         <p>Now that the website is up and running, we're working hard to finalize some additional details for the 2013 event. In particular, we can tell you that the full-day conference will be $99, and registration will be open in the next couple of weeks. One of our sponsors, ThunderTix, has graciously offered to host our event registration this year, but we still have some work to do on our end in order to get things properly set up.</p>
         <p>On the speaker front, you may have noticed that we've listed a few speakers for the 2013 event on our home page. We've already contacted several awesome folks about melting out brains with their expertise this time around, but that doesn't mean we don't have room for you! In the next week, we'll be opening up our CfP, and we'd love to hear about the awesome stuff you want to share. Of course, if casual is more your style, we'll also be bringing back open spaces this year, so get those topics ready!</p>
         <p>New to HTML5.tx this year will be two full-day CSS and JavaScript training classes offered by a couple of our killer speakers. Tickets for these will be offered separately and in combo-packs with the main event, and will go on sale when full registration opens in a few weeks. We're still hammering out details for the location and price, but stay tuned for updates here.</p>
      </div>
      <div class="frame content-frame">
         <h3>The New HTML5.tx Site is Live!</h3>
         <p>09.16.2012</p>
         <p>Today, we launched the new, re-branded HTML5.tx! Our design partners at Drifting Creatives did an amazing job once again this year, and we're really excited to share the "look and feel" of our 2013 event with you.</p>
         <p>For our next iteration of HTML5.tx, we wanted to focus on both the growth and promise of HTML5, as well as its promise for a utopian or dystopian future, depending on who's hype you choose to believe. Those of us who love the web and make our living on it certainly believe in HTML5, but the question still remains: what does the future of the web really look like?</p>
         <p>HTML5.tx 2013 will be about exactly that: how this movement called HTML5 affects us all: developer to designer; Front-ender to back-ender; and from the desktop to the mobile device. We hope you'll join us on February 2nd, 2013 to embrace and explore the future of the web.</p>
      </div>
   </section>
   <section class="column last column-deem content-frame">
      <h2>Important Info</h2>
      <p>HTML5.tx is the premier event for web designers, developers and technologists in Texas. Our <a href="http://2011.html5tx.com/">inaugural event</a> was held in Austin, in 2011 and the second edition is slated for Feb 2nd, 2013. Check out the <a href="https://vimeo.com/36094284">promo video</a> for a recap of last year's event, and to get a preview of what's in store for 2013.</p>
   </section>
</div>

app/views/pages/contact.html.erb
<div class="group" role="main">
   <section class="column frame content-frame">
      <h2>Contact Us</h2>
      <p>Have a question or comment for us? Perhaps we can help. Drop us a line at <a href="mailto:event@html5tx.com">event@html5tx.com</a>.</p>
   <p>Interested in sponsoring? Email us directly at <a href="mailto:sponsorship@html5tx.com">sponsorship@html5tx.com</a>.</p>
   </section>
   <section class="column last">
      <iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=St.+Edward's+University+Ragsdale+Center+Austin,+TX&amp;aq=&amp;sll=31.168934,-100.076842&amp;sspn=17.815351,28.54248&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Ragsdale+Center,+Moody,+Austin,+Texas+78704&amp;ll=30.22947,-97.756525&amp;spn=0.006227,0.006968&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
   </section>
</div>

app/views/pages/index.html.erb
<div class="group" role="main">
  <section class="column frame frame-overview textured">
    <p><em><strong>HTML5.tx</strong> is sold out!</em></p>
    <p>Have a spare ticket? <a href="mailto:event@html5tx.com?subject=I have a spare ticket!">Let us know!</a></p>
    <p>HTML5.tx is a premium-grade conference for all things HTML, CSS and JavaScript. Our inaugural event was held in Austin, in 2011 and the second edition is slated for Feb 2nd, 2013.</p>
  </section>
  <section class="column last frame frame-overview textured">
     <p><strong>HTML5.TX</strong></p>
     <p><strong>February 02, 2013</strong></p>
     <p><strong>AUSTIN, TEXAS</strong></p>
     <p><strong>St. Edward's University, Ragsdale Center</strong></p>
  </section>
</div>
<!--<div class="group textured" role="main">
  <a class="btn-video" href="#">Play Video</a>
</div>-->
<div class="group" role="main">
  <ul class="l-featured cogs">
     <li><a class="speaker speaker-estelle" href="/pages/speakers#estelle">Estelle Weyl<span class="static"></span></a><span class="cog cog-xl"></span></li>
     <li><a class="speaker speaker-mike" href="/pages/speakers#mike">Mike Taylor<span class="static"></span></a><span class="cog cog-xl"></span></li>
     <li><a class="speaker speaker-garann" href="/pages/speakers#garann">Garann Means<span class="static"></span></a><span class="cog cog-xl"></span></li>
     <li class="last"><a class="speaker speaker-christopher" href="/pages/speakers#christopher">Christopher Schmitt<span class="static"></span></a><span class="cog cog-xl"></span></li>
  </ul>
</div>
<div class="group" role="main">
  <ul class="l-featured">
     <li><a class="sponsor sponsor-kendoui" href="/pages/sponsors#kendoui">KendoUI</a></li>
     <li><a class="sponsor sponsor-adobe" href="/pages/sponsors#adobe">Adobe</a></li>
     <li><a class="sponsor sponsor-capital-factory" href="/pages/sponsors#capital-factory">Capital Factory</a></li>
     <li class="last"><a class="sponsor sponsor-four-kitchens" href="/pages/sponsors#four-kitchens">Four Kitchens</a></li>
  </ul>
</div>

app/views/pages/talk.html.erb
<h1>Pages#talk</h1>
<p>Find me in app/views/pages/talk.html.erb</p>

app/views/pages/venue.html.erb
<h1>Pages#venue</h1>
<p>Find me in app/views/pages/venue.html.erb</p>

app/views/pages/videos.html.erb
<h1>Pages#videos</h1>
<p>Find me in app/views/pages/videos.html.erb</p>